---
apiVersion: v1
kind: Namespace
metadata:
  name: dummy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy
  namespace: dummy
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/dummy
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
