---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

# Kube-prometheus-stack
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "79.2.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h
  values:
    grafana:
      adminUser: admin
      adminPassword: admin
      service:
        enabled: true
        type: ClusterIP
        port: 3000
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-loki-distributed-gateway.monitoring.svc.cluster.local:80
          isDefault: false
          editable: true
    prometheus:
      prometheusSpec:
        retention: 15d
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
    # alertmanager:
    #   alertmanagerSpec:
    #     resources:
    #       requests:
    #         memory: 256Mi
    #         cpu: 100m
    #       limits:
    #         memory: 512Mi
    #         cpu: 200m
    # nodeExporter:
    #   resources:
    #     requests:
    #       memory: 128Mi
    #       cpu: 100m
    #     limits:
    #       memory: 256Mi
    #       cpu: 200m

# Loki
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki-distributed
      version: "0.80.6"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    loki:
      storageConfig:
        boltdb_shipper:
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks
    ingester:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path
    querier:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: local-path

# Fluent Bit
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent
  namespace: monitoring
spec:
  interval: 24h
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: fluent-bit
      version: "0.54.0"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: monitoring
      interval: 12h
  values:
    config:
      service: |
        [SERVICE]
            Daemon Off
            Flush 1
            Log_Level info
            Parsers_File /fluent-bit/etc/parsers.conf
            Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port 2020
            Health_Check On

      customParsers: |
        [MULTILINE_PARSER]
            Name          python-exception
            Type          regex
            Flush_timeout 1000
            # Match Python stack traces and multi-line errors
            # Lines that don't start with a timestamp or common log level indicators
            Rule      "start_state"   "/^(\d{4}-\d{2}-\d{2}|[A-Z][a-z]{2} \d{1,2}|INFO|ERROR|WARNING|DEBUG)/"  "cont"
            Rule      "cont"          "/^(?!\d{4}-\d{2}-\d{2}|[A-Z][a-z]{2} \d{1,2}|INFO|ERROR|WARNING|DEBUG)/"  "cont"

      inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*_starlink_*.log
            multiline.parser docker, cri, python-exception
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines Off

      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Kube_URL https://kubernetes.default.svc:443
            Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_Tag_Prefix kube.var.log.containers.
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
            Labels On
            Annotations Off

        [FILTER]
            Name grep
            Match kube.*
            Regex $kubernetes['namespace_name'] ^starlink$

      outputs: |
        [OUTPUT]
            Name loki
            Match kube.*
            Host loki-loki-distributed-gateway.monitoring.svc.cluster.local
            Port 80
            Labels job=fluent-bit
            Label_keys $kubernetes['namespace_name'],$kubernetes['pod_name'],$kubernetes['container_name'],$kubernetes['labels']['app']
            Remove_keys kubernetes,stream
            Auto_kubernetes_labels On

    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

    tolerations:
      - effect: NoSchedule
        operator: Exists

    serviceMonitor:
      enabled: false
