---
apiVersion: v1
kind: Namespace
metadata:
  name: notanapp
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notanapp
  namespace: notanapp
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/webservice
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
