---
apiVersion: v1
kind: Namespace
metadata:
  name: ollama
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 24h
  url: https://helm.otwld.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  interval: 10m
  chart:
    spec:
      chart: ollama
      version: "1.32.0"
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: ollama
      interval: 12h
  values:
    replicaCount: 1
    ollama:
      gpu:
        enabled: true
        type: nvidia
        number: 1
        nvidiaResource: "nvidia.com/gpu"

    runtimeClassName: nvidia
    nodeSelector:
      nvidia.com/gpu.present: "true"

    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 8Gi

    persistentVolume:
      enabled: true
      size: 50Gi
      storageClass: ""
      accessModes:
        - ReadWriteOnce
