---
apiVersion: v1
kind: Namespace
metadata:
  name: potato
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: potato
  namespace: potato
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/webservice
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/radeksh/potato
      tag: latest
      pullPolicy: Always
    service:
      type: LoadBalancer
      port: 50000
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 32Mi
